### ISSUE TITLE
como arreglar esto cada vez que inicio busqueda me salta este error (SOLUCIONADO)

### ISSUE THREAD

**Issue by sirhof** [XDeadHackerX/The_spy_job#1]
#################################
[☢] UserName: ****Ç
#################################

Abriendo Navegador....
Contraseña: 
su: Fallo de autenticación

 siempre salta fallo de autenticacion no se en que puede fallar, debeser la api o como puedo arregarlaro 
gracias

**Comment by sirhof** [comment]
que es lo que tengo mal confiurado ? @XDeadHackerX

**Comment by sirhof** [comment]
arreglado,eran problemas de escritura en la carpeta que habia clonado el repositorio :D

**Comment by XDeadHackerX** [comment]
Dentro del Apartado “[0] Instalar y Configurar Requisitos” cuando presionamos la Opción “[1] Instalar requisitos” no pide que pongamos un usuario sin privilegios de SuperUsuario/root este paso es muy importante, ya que se almacena ese usuario para a la hora de abrir un Navegador desde la Terminal pueda hacerlo sin ningún problema. También puede dar este error si no le das permisos de root a la Herramienta o no la lanzas desde una Terminal como root.
