### ISSUE TITLE
 sudo: ignorant: command not found

### ISSUE THREAD

**Issue by head69100** [XDeadHackerX/The_spy_job#5]
Hi, when i press 6 (for phone ) then 1 2 3 4 5 all command say that error : 
sudo: ignorant: command not found

Why ? and how fix it ?

**Comment by XDeadHackerX** [comment]
Good afternoon, I apologize for the delay. The error suggests that either the command has been written incorrectly (which seems unlikely, considering it is a script) or that all the necessary dependencies have not been downloaded. Here is a comprehensive guide to resolving the issue. Please note that this tool is designed to function only on Debian-derived operating systems.

0) Install and use the Tool with Root

1) sudo apt update && apt -y full-upgrade

2) sudo apt-get install git

3) git clone https://github.com/XDeadHackerX/The_spy_job.git

4) cd The_spy_job

5) chmod 777 the_spy_job.sh

6) bash the_spy_job.sh

7) Check Option 0 and then 1 to install the dependencies (Only check the first time)

Best regards and I look forward to your response.
